### ISSUE TITLE
tp 5,6,7,8

### ISSUE THREAD

**Issue by csimonelli** [fiuba-labo-de-micro-miercoles/2019-2c-trabajo-practico-simonelli_1ro_2020#5]
Hola, subí los codigos de los tp 5,6,7,8. Todos andan, probados en hardware, voy a estar pasando los informes en el transcurso del fin de semana. Me gustaría que si pueden le den un vistazo, para ver que están bien.
Saludos.

**Comment by fbaglivo** [comment]
Hola! No encuentro el pdf del TP7. Por favor, crea un issue por TP.

Saludos!
